In [1]:
# 1
import pandas as pd
print(pd.__version__)
print(pd.show_versions(as_json=True))

0.24.2
{'system': {'commit': None, 'python': '3.7.3.final.0', 'python-bits': 64, 'OS': 'Windows', 'OS-release': '10', 'machine': 'AMD64', 'processor': 'Intel64 Family 6 Model 142 Stepping 10, GenuineIntel', 'byteorder': 'little', 'LC_ALL': 'None', 'LANG': 'None', 'LOCALE': 'None.None'}, 'dependencies': {'pandas': '0.24.2', 'pytest': '4.3.1', 'pip': '19.0.3', 'setuptools': '40.8.0', 'Cython': '0.29.6', 'numpy': '1.16.2', 'scipy': '1.2.1', 'pyarrow': None, 'xarray': None, 'IPython': '7.4.0', 'sphinx': '1.8.5', 'patsy': '0.5.1', 'dateutil': '2.8.0', 'pytz': '2018.9', 'blosc': None, 'bottleneck': '1.2.1', 'tables': '3.5.1', 'numexpr': '2.6.9', 'feather': None, 'matplotlib': '3.0.3', 'openpyxl': '2.6.1', 'xlrd': '1.2.0', 'xlwt': '1.3.0', 'xlsxwriter': '1.1.5', 'lxml.etree': '4.3.2', 'bs4': '4.7.1', 'html5lib': '1.0.1', 'sqlalchemy': '1.3.1', 'pymysql': None, 'psycopg2': None, 'jinja2': '2.10', 's3fs': None, 'fastparquet': None, 'pandas_gbq': None, 'pandas_datareader': '0.8.1', 'gcsfs': None

In [2]:
# 2
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

ser1 = pd.Series(mylist)
ser2 = pd.Series(myarr)
ser3 = pd.Series(mydict)
print(ser1);print(ser2);print(ser3)

0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int32
a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64


In [3]:
# 3
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)

df = ser.to_frame().reset_index()
print(df.head())

  index  0
0     a  0
1     b  1
2     c  2
3     e  3
4     d  4


In [5]:
# 4
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

df = pd.DataFrame({'col1': ser1, 'col2': ser2})
print(df.head())

  col1  col2
0    a     0
1    b     1
2    c     2
3    e     3
4    d     4


In [6]:
# 5
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser.name = 'alphabets'
ser.head()

0    a
1    b
2    c
3    e
4    d
Name: alphabets, dtype: object

In [7]:
# 6
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
ser1[~ser1.isin(ser2)]

0    1
1    2
2    3
dtype: int64

In [8]:
# 7
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

ser_u = pd.Series(np.union1d(ser1, ser2))  # union
ser_i = pd.Series(np.intersect1d(ser1, ser2))  # intersect
ser_u[~ser_u.isin(ser_i)]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [9]:
# 8
state = np.random.RandomState(100)
ser = pd.Series(state.normal(10, 5, 25))
np.percentile(ser, q=[0, 25, 50, 75, 100])

array([ 1.25117263,  7.70986507, 10.92259345, 13.36360403, 18.0949083 ])

In [10]:
# 9
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
ser.value_counts()

a    6
d    5
f    4
c    4
b    3
g    3
h    3
e    2
dtype: int64

In [11]:
# 10
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))
print("Top 2 Freq:", ser.value_counts())
ser[~ser.isin(ser.value_counts().index[:2])] = 'Other'
ser

Top 2 Freq: 1    6
4    4
2    2
dtype: int64


0     Other
1         1
2         4
3         4
4         4
5         1
6     Other
7         1
8         1
9         1
10        1
11        4
dtype: object

In [12]:
# 11
ser = pd.Series(np.random.random(20))
pd.qcut(ser, q=[0, .10, .20, .3, .4, .5, .6, .7, .8, .9, 1], 
        labels=['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th']).head()

0    4th
1    3rd
2    9th
3    6th
4    2nd
dtype: category
Categories (10, object): [1st < 2nd < 3rd < 4th ... 7th < 8th < 9th < 10th]

In [13]:
# 12
ser = pd.Series(np.random.randint(1, 10, 35))
df = pd.DataFrame(ser.values.reshape(7,5))
print(df)

   0  1  2  3  4
0  5  1  8  9  9
1  1  1  4  6  1
2  6  7  8  5  9
3  8  5  2  9  8
4  9  4  2  4  2
5  4  5  9  4  6
6  4  5  8  2  8


In [14]:
# 13
ser = pd.Series(np.random.randint(1, 10, 7))
np.argwhere(ser % 3==0)

C:\Users\JIC\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:56: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  return getattr(obj, method)(*args, **kwds)


array([[0]], dtype=int64)

In [16]:
# 14
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]
ser.take(pos)

0     a
4     e
8     i
14    o
20    u
dtype: object

In [18]:
# 15
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))
# vertical
ser1.append(ser2)

0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
4    e
dtype: object

In [19]:
# horizontal
df = pd.concat([ser1, ser2], axis=1)
print(df)

   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e


In [20]:
# 16
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])
[pd.Index(ser1).get_loc(i) for i in ser2]

[5, 4, 0, 8]

In [21]:
# 17
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)
np.mean((truth-pred)**2)

0.26333091577992807

In [23]:
# 18
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
ser.map(lambda x: x[0].upper() + x[1:])

0     How
1      To
2    Kick
3    Ass?
dtype: object

In [24]:
# 19
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
ser.map(lambda x: len(x))

0    3
1    2
2    4
3    4
dtype: int64

In [25]:
# 20
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])
print(ser.diff().tolist())
print(ser.diff().diff().tolist())

[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]
[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]


In [26]:
# 21
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
pd.to_datetime(ser)

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

In [27]:
# 22
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
from dateutil.parser import parse
ser_ts = ser.map(lambda x: parse(x))

print("Date: ", ser_ts.dt.day.tolist())
print("Week number: ", ser_ts.dt.weekofyear.tolist())
print("Day number of year: ", ser_ts.dt.dayofyear.tolist())
print("Day of week: ", ser_ts.dt.weekday_name.tolist())

Date:  [1, 2, 3, 4, 5, 6]
Week number:  [53, 5, 9, 14, 19, 23]
Day number of year:  [1, 33, 63, 94, 125, 157]
Day of week:  ['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']


In [28]:
# 23
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])
ser.map(lambda x: parse('04 ' + x))

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]

In [30]:
# 24
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])
from collections import Counter
mask = ser.map(lambda x: sum([Counter(x.lower()).get(i, 0) for i in list('e')]) >= 1)
ser[mask]

0     Apple
1    Orange
4     Money
dtype: object

In [32]:
# 25
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'
import re
[x[0] for x in [re.findall(pattern, email) for email in emails] if len(x) > 0]

['rameses@egypt.com', 'matt@t.co', 'narendra@modi.com']

In [35]:
# 26
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
weights.groupby(fruit).mean()

apple     6.333333
banana    6.000000
carrot    4.500000
dtype: float64

In [36]:
# 27
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])
np.linalg.norm(p-q)

18.16590212458495

In [37]:
# 28
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])
dd = np.diff(np.sign(np.diff(ser)))
peak_locs = np.where(dd == -2)[0] + 1
peak_locs

array([1, 5, 7], dtype=int64)

In [38]:
# 29
my_str = 'dbc deb abed gade'
ser = pd.Series(list('dbc deb abed gade'))
freq = ser.value_counts()
print(freq)
least_freq = freq.dropna().index[-1]
"".join(ser.replace(' ', least_freq))

d    4
     3
b    3
e    3
a    2
g    1
c    1
dtype: int64


'dbccdebcabedcgade'

In [39]:
# 30
ser = pd.Series(np.random.randint(1,10,10), pd.date_range('2000-01-01', periods=10, freq='W-SAT'))
ser

2000-01-01    7
2000-01-08    1
2000-01-15    5
2000-01-22    5
2000-01-29    6
2000-02-05    8
2000-02-12    9
2000-02-19    5
2000-02-26    4
2000-03-04    2
Freq: W-SAT, dtype: int32

In [40]:
# 31
ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
ser.resample('D').ffill() 

2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     NaN
Freq: D, dtype: float64

In [41]:
# 32
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))
autocorrelations = [ser.autocorr(i).round(2) for i in range(11)]
print(autocorrelations[1:])
print('Lag having highest correlation: ', np.argmax(np.abs(autocorrelations[1:]))+1)

[0.15, -0.03, -0.06, -0.5, 0.04, 0.25, 0.01, 0.13, -0.11, -0.49]
Lag having highest correlation:  4


In [43]:
# 33
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', chunksize=50)
df2 = pd.DataFrame()
for chunk in df:
    df2 = df2.append(chunk.iloc[0,:])
print(df2.head())

      age       b  chas     crim     dis  indus  lstat  medv    nox  ptratio  \
0    65.2  396.90   0.0  0.00632  4.0900   2.31   4.98  24.0  0.538     15.3   
50   45.7  395.56   0.0  0.08873  6.8147   5.64  13.45  19.7  0.439     16.8   
100  79.9  394.76   0.0  0.14866  2.7778   8.56   9.42  27.5  0.520     20.9   
150  97.3  372.80   0.0  1.65660  1.6180  19.58  14.10  21.5  0.871     14.7   
200  13.9  384.30   0.0  0.01778  7.6534   1.47   4.45  32.9  0.403     17.0   

     rad     rm    tax    zn  
0    1.0  6.575  296.0  18.0  
50   4.0  5.963  243.0  21.0  
100  5.0  6.727  384.0   0.0  
150  5.0  6.122  403.0   0.0  
200  3.0  7.135  402.0  95.0  


In [47]:
# 34
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', 
                 converters={'medv': lambda x: 'High' if float(x) > 25 else 'Low'})
print(df.head())

      crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98   Low  
1  396.90   9.14   Low  
2  392.83   4.03  High  
3  394.63   2.94  High  
4  396.90   5.33  High  


In [48]:
# 35
L = pd.Series(range(15))
def gen_strides(a, stride_len=5, window_len=5):
    n_strides = ((a.size-window_len)//stride_len) + 1
    return np.array([a[s:(s+window_len)] for s in np.arange(0, a.size, stride_len)[:n_strides]])

gen_strides(L, stride_len=2, window_len=4)

array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13]], dtype=int64)

In [52]:
# 36
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', usecols=['crim', 'medv'])
print(df.head())

      crim  medv
0  0.00632  24.0
1  0.02731  21.6
2  0.02729  34.7
3  0.03237  33.4
4  0.06905  36.2


In [53]:
# 37
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
#  number of rows and columns
print(df.shape)
# datatypes
print(df.dtypes)
# how many columns under each dtype
print(df.get_dtype_counts())
print(df.dtypes.value_counts())
# summary statistics
df_stats = df.describe()
# numpy array 
df_arr = df.values
# list
df_list = df.values.tolist()

(93, 27)
Manufacturer           object
Model                  object
Type                   object
Min.Price             float64
Price                 float64
Max.Price             float64
MPG.city              float64
MPG.highway           float64
AirBags                object
DriveTrain             object
Cylinders              object
EngineSize            float64
Horsepower            float64
RPM                   float64
Rev.per.mile          float64
Man.trans.avail        object
Fuel.tank.capacity    float64
Passengers            float64
Length                float64
Wheelbase             float64
Width                 float64
Turn.circle           float64
Rear.seat.room        float64
Luggage.room          float64
Weight                float64
Origin                 object
Make                   object
dtype: object
float64    18
object      9
dtype: int64
float64    18
object      9
dtype: int64


In [54]:
# 38
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
# Get Manufacturer with highest price
df.loc[df.Price == np.max(df.Price), ['Manufacturer', 'Model', 'Type']]

# Get Row and Column number
row, col = np.where(df.values == np.max(df.Price))

# Get the value
df.iat[row[0], col[0]]
df.iloc[row[0], col[0]]

61.9

In [55]:
# 39
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df=df.rename(columns = {'Type':'CarType'})
df.columns = df.columns.map(lambda x: x.replace('.', '_'))
print(df.columns)

Index(['Manufacturer', 'Model', 'CarType', 'Min_Price', 'Price', 'Max_Price',
       'MPG_city', 'MPG_highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev_per_mile', 'Man_trans_avail',
       'Fuel_tank_capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn_circle', 'Rear_seat_room', 'Luggage_room', 'Weight', 'Origin',
       'Make'],
      dtype='object')


In [56]:
# 40
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df.isnull().values.any()

True

In [57]:
# 41
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
n_missings_each_col = df.apply(lambda x: x.isnull().sum())
n_missings_each_col.argmax()

C:\Users\JIC\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: 
The current behaviour of 'Series.argmax' is deprecated, use 'idxmax'
instead.
The behavior of 'argmax' will be corrected to return the positional
maximum in the future. For now, use 'series.values.argmax' or
'np.argmax(np.array(values))' to get the position of the maximum
row.
  after removing the cwd from sys.path.


'Luggage.room'

In [58]:
# 42
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df_out = df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(lambda x: x.fillna(x.mean()))
print(df_out.head())

   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


In [59]:
# 43
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
d = {'Min.Price': np.nanmean, 'Max.Price': np.nanmedian}
df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(lambda x, d: x.fillna(d[x.name](x)), args=(d, ))

In [62]:
# 44
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
type(df.loc[:, ['a']])

pandas.core.frame.DataFrame

In [63]:
# 45
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

# Solution 1
df[list('cbade')]

# Solution 2
def switch_columns(df, col1=None, col2=None):
    colnames = df.columns.tolist()
    i1, i2 = colnames.index(col1), colnames.index(col2)
    colnames[i2], colnames[i1] = colnames[i1], colnames[i2]
    return df[colnames]

df1 = switch_columns(df, 'a', 'c')

# Solution 3
df[sorted(df.columns)]

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [68]:
# 46
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
pd.set_option('display.max_columns', 10)
pd.set_option('display.max_rows', 10)
b=pd.set_option('display.max_rows', 10)

In [69]:
# 47
df = pd.DataFrame(np.random.random(4)**10, columns=['random'])
df.round(4)

random
0  0.0003
1  0.2593
2  0.0203
3  0.0000

In [70]:
# 48
df = pd.DataFrame(np.random.random(4), columns=['random'])

out = df.style.format({
    'random': '{0:.2%}'.format,
})

out

In [71]:
# 49
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df.iloc[::20, :][['Manufacturer', 'Model', 'Type']])

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [72]:
# 50
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])
df[['Manufacturer', 'Model', 'Type']] = df[['Manufacturer', 'Model', 'Type']].fillna('missing')
df.index = df.Manufacturer + '_' + df.Model + '_' + df.Type
print(df.index.is_unique)

True


In [76]:
# 51
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))
n=5
df['a'].argsort()[::-1][n]

3

In [77]:
# 52
ser = pd.Series(np.random.randint(1, 100, 15))
print('ser: ', ser.tolist(), 'mean: ', round(ser.mean()))
np.argwhere(ser > ser.mean())[1]

ser:  [3, 53, 9, 89, 9, 62, 59, 89, 94, 4, 48, 40, 8, 3, 54] mean:  42


C:\Users\JIC\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:56: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  return getattr(obj, method)(*args, **kwds)


array([3], dtype=int64)

In [79]:
# 53
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
last_two_rows = df.iloc[np.where(df.apply(np.sum, axis=1) > 100)[0][-2:], :]
last_two_rows

0   1   2   3
11  28  28  27  33
14  11  28  34  30

In [80]:
# 54
ser = pd.Series(np.logspace(-2, 2, 30))
def cap_outliers(ser, low_perc, high_perc):
    low, high = ser.quantile([low_perc, high_perc])
    print(low_perc, '%ile: ', low, '|', high_perc, '%ile: ', high)
    ser[ser < low] = low
    ser[ser > high] = high
    return(ser)

capped_ser = cap_outliers(ser, .05, .95)
capped_ser

0.05 %ile:  0.016049294076965887 | 0.95 %ile:  63.876672220183934


0      0.016049
1      0.016049
2      0.018874
3      0.025929
4      0.035622
        ...    
25    28.072162
26    38.566204
27    52.983169
28    63.876672
29    63.876672
Length: 30, dtype: float64

In [81]:
# 55
df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10,-1))
# Negative value removed
arr = df[df > 0].values.flatten()
arr_qualified = arr[~np.isnan(arr)]

# find side-length of largest possible square
n = int(np.floor(arr_qualified.shape[0]**.5))

# Take top n^2 items without changing positions
top_indexes = np.argsort(arr_qualified)[::-1]
output = np.take(arr_qualified, sorted(top_indexes[:n**2])).reshape(n, -1)
print(output)

[[16. 46. 16. 32. 16. 11. 23. 34.]
 [22. 25. 24. 48. 28. 40. 42. 39.]
 [37. 20. 10. 19. 30.  9. 42. 28.]
 [30. 13. 45. 35.  9. 40. 38. 17.]
 [38. 42. 33. 10. 19. 26. 18. 41.]
 [22. 32. 39. 17. 40. 41. 40. 43.]
 [ 8. 36. 14. 43. 13. 29. 42. 41.]
 [21.  7. 39. 36. 16. 46. 15. 12.]]


In [82]:
# 56
df = pd.DataFrame(np.arange(25).reshape(5, -1))
def swap_rows(df, i1, i2):
    a, b = df.iloc[i1, :].copy(), df.iloc[i2, :].copy()
    df.iloc[i1, :], df.iloc[i2, :] = b, a
    return df

print(swap_rows(df, 1, 2))

    0   1   2   3   4
0   0   1   2   3   4
1  10  11  12  13  14
2   5   6   7   8   9
3  15  16  17  18  19
4  20  21  22  23  24


In [83]:
# 57
df = pd.DataFrame(np.arange(25).reshape(5, -1))
df.iloc[::-1, :]

0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4

In [85]:
# 58
df = pd.DataFrame(np.arange(25).reshape(5,-1), columns=list('abcde'))
df_onehot = pd.concat([pd.get_dummies(df['a']), df[list('bcde')]], axis=1)
df_onehot

0  5  10  15  20   b   c   d   e
0  1  0   0   0   0   1   2   3   4
1  0  1   0   0   0   6   7   8   9
2  0  0   1   0   0  11  12  13  14
3  0  0   0   1   0  16  17  18  19
4  0  0   0   0   1  21  22  23  24

In [86]:
# 59
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1))
print('Column with highest row maxes: ', df.apply(np.argmax, axis=1).value_counts().index[0])

Column with highest row maxes:  1


C:\Users\JIC\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:56: FutureWarning: 
The current behaviour of 'Series.argmax' is deprecated, use 'idxmax'
instead.
The behavior of 'argmax' will be corrected to return the positional
maximum in the future. For now, use 'series.values.argmax' or
'np.argmax(np.array(values))' to get the position of the maximum
row.
  return getattr(obj, method)(*args, **kwds)


In [88]:
# 60
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1), columns=list('pqrs'), index=list('abcdefghij'))
import numpy as np
nearest_rows = []
nearest_distance = []

for i, row in df.iterrows():
    curr = row
    rest = df.drop(i)
    e_dists = {}
    for j, contestant in rest.iterrows():
        e_dists.update({j: round(np.linalg.norm(curr.values - contestant.values))})
    nearest_rows.append(max(e_dists, key=e_dists.get))
    nearest_distance.append(max(e_dists.values()))

df['nearest_row'] = nearest_rows
df['dist'] = nearest_distance
df

p   q   r   s nearest_row   dist
a  75   1  77   9           e  128.0
b  98  22  95   8           e  130.0
c  86  76  35  20           j  130.0
d  91  32  45   9           e  127.0
e  11  84  85  82           b  130.0
f  67  60  23  50           j  103.0
g  14  48  79  15           b   90.0
h  79  59  82   5           j  120.0
i  35  39  37  76           b  111.0
j   5  23  84  92           c  130.0

In [89]:
# 61
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1), columns=list('pqrstuvwxy'), index=list('abcdefgh'))
abs_corrmat = np.abs(df.corr())
max_corr = abs_corrmat.apply(lambda x: sorted(x)[-2])
print('Maximum Correlation possible for each column: ', np.round(max_corr.tolist(), 2))

Maximum Correlation possible for each column:  [0.74 0.7  0.78 0.5  0.44 0.78 0.77 0.77 0.32 0.67]


In [91]:
# 62
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
min_by_max = df.apply(lambda x: np.min(x)/np.max(x), axis=1)
min_by_max

0    0.076087
1    0.032609
2    0.114583
3    0.134146
4    0.104651
5    0.106667
6    0.191919
7    0.395833
dtype: float64

In [93]:
# 63
f = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
out = df.apply(lambda x: x.sort_values().unique()[-2], axis=1)
df['penultimate'] = out
df

0   1   2   3   4  ...   6   7   8   9  penultimate
0  41   8  87  40  65  ...  83  62  92  84           87
1   3  45  78  30  78  ...  26  74  58  52           78
2  96  18  25  11  12  ...  96  43  85  80           93
3  55  18  40  53  11  ...  15  47  68  71           71
4  23  45  56  69   9  ...  86  78  70  55           78
5  26   8  63  24  28  ...  48  74  59  20           74
6  33  62  39  62  26  ...  19  20  53  99           95
7  74  79  40  38  83  ...  96  86  48  38           86

[8 rows x 11 columns]

In [95]:
# 64
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

# 64-1
out1 = df.apply(lambda x: ((x - x.mean())/x.std()).round(2))

# 64-2
out2 = df.apply(lambda x: ((x.max() - x)/(x.max() - x.min())).round(2))

out1 ; out2

0     1     2     3     4     5     6     7     8     9
0  0.71  0.93  0.82  0.61  0.39  1.00  0.39  0.00  0.56  0.00
1  0.99  0.92  0.75  0.51  0.00  0.28  0.07  0.08  1.00  1.00
2  0.35  0.28  1.00  0.98  0.39  0.78  0.17  0.30  1.00  0.85
3  0.52  0.48  0.46  0.02  0.15  0.73  0.89  0.18  0.55  0.75
4  0.03  1.00  0.66  0.00  0.82  0.37  1.00  1.00  0.98  0.79
5  0.00  0.00  0.41  0.84  1.00  0.00  0.33  0.40  0.93  0.91
6  1.00  0.88  0.00  1.00  0.87  0.82  0.30  0.76  0.39  0.66
7  0.32  0.75  0.10  0.96  0.63  0.86  0.00  0.57  0.00  0.00

In [96]:
# 65
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
[df.iloc[i].corr(df.iloc[i+1]).round(2) for i in range(df.shape[0])[:-1]]

[0.44, 0.54, 0.42, 0.07, 0.22, -0.21, -0.25]

In [98]:
# 66
df = pd.DataFrame(np.random.randint(1,100, 100).reshape(10, -1))
for i in range(df.shape[0]):
    df.iat[i, i] = 0
    df.iat[df.shape[0]-i-1, i] = 0
df

0   1   2   3   4   5   6   7   8   9
0   0  29  42  24  47  72  81  54  74   0
1  72   0  81  85  20  62  29   7   0  70
2  29  15   0  95   7  69  73   0  25  24
3  70  68  57   0  86  92   0   3  78  22
4  99  96  97  58   0   0  64  11  58  35
5  66   4   2  40   0   0  41  54  38  52
6  45  65  78   0  12  89   0  27  28  14
7  90  74   0  97  68  59   3   0  16  25
8  94   0   1  12  97  14  25   3   0  13
9   0   5  60  82  23  26  61  99   9   0

In [99]:
# 67
df = pd.DataFrame({'col1': ['apple', 'banana', 'orange'] * 3,
                   'col2': np.random.rand(9),
                   'col3': np.random.randint(0, 15, 9)})
df_grouped = df.groupby(['col1'])

df_grouped.get_group('apple')

col1      col2  col3
0  apple  0.787579     6
3  apple  0.951887    10
6  apple  0.840903    13

In [102]:
# 68
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'taste': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})
df['taste'].groupby(df.fruit).get_group('banana').sort_values().iloc[-2]

0.48094948645640334

In [103]:
# 69
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})
out = df.groupby('fruit', as_index=False)['price'].mean()
print(out)

    fruit      price
0   apple   5.333333
1  banana   7.000000
2  orange  11.333333


In [106]:
# 70
df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'pounds': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})

pd.merge(df1, df2, how='inner', left_on=['fruit', 'weight'], right_on=['pazham', 'pounds'], suffixes=['_left', '_right'])

fruit weight  price_left  pazham pounds  price_right
0   apple   high          12   apple   high           10
1   apple   high           4   apple   high           10
2   apple   high          14   apple   high           10
3  orange    low           0  orange    low            7
4  orange    low           1  orange    low            7
5  orange    low          10  orange    low            7

In [108]:
# 71
df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})
print(df1[~df1.isin(df2).all(1)])

    fruit  weight  price
0   apple    high      0
1  banana  medium      9
2  orange     low      6
3   apple    high      1
4  banana  medium     12
5  orange     low      8
6   apple    high      2
7  banana  medium      0
8  orange     low      3


In [109]:
# 72
df = pd.DataFrame({'fruit1': np.random.choice(['apple', 'orange', 'banana'], 10),
                    'fruit2': np.random.choice(['apple', 'orange', 'banana'], 10)})
np.where(df.fruit1 == df.fruit2)

(array([1, 3, 4], dtype=int64),)

In [110]:
# 73
df = pd.DataFrame(np.random.randint(1, 100, 20).reshape(-1, 4), columns = list('abcd'))
df['a_lag1'] = df['a'].shift(1)
df['b_lead1'] = df['b'].shift(-1)
print(df)

    a   b   c   d  a_lag1  b_lead1
0  37  84  49  87     NaN     24.0
1  72  24   1  24    37.0      8.0
2   4   8  28   7    72.0     52.0
3   8  52  28  19     4.0     37.0
4  83  37  60  42     8.0      NaN


In [111]:
# 74
df = pd.DataFrame(np.random.randint(1, 10, 20).reshape(-1, 4), columns = list('abcd'))
pd.value_counts(df.values.ravel())

2    8
8    3
9    2
5    2
4    2
3    2
7    1
dtype: int64

In [112]:
# 75
df = pd.DataFrame(["STD, City    State",
"33, Kolkata    West Bengal",
"44, Chennai    Tamil Nadu",
"40, Hyderabad    Telengana",
"80, Bangalore    Karnataka"], columns=['row'])

df_out = df.row.str.split(',|\t', expand=True)
new_header = df_out.iloc[0]
df_out = df_out[1:]
df_out.columns = new_header
print(df_out)

0 STD            City    State
1  33   Kolkata    West Bengal
2  44    Chennai    Tamil Nadu
3  40   Hyderabad    Telengana
4  80   Bangalore    Karnataka
