In [2]:
#1
import numpy as np
print(np.__version__)

1.16.5


In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.full((3,3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [5]:
arr=np.arange(10)
arr[arr%2==1]

array([1, 3, 5, 7, 9])

In [6]:
arr[arr%2==1]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [7]:
arr=np.arange(10)
arr_copy=arr.copy()
arr_copy[arr_copy%2==1]=-1
print(arr_copy)
arr

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
a=np.arange(10).reshape(2,-1)
b=np.repeat(1,10).reshape(2,-1)
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [11]:
a=np.array([1,2,3])
print(np.repeat(a,3))
print(np.tile(a,3))
np.r_[np.repeat(a,3),np.tile(a,3)]

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [12]:
a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [13]:
a=np.array([1,2,3,4,5])
b=np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [14]:
a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

In [15]:
a=np.array([2,6,1,9,10,3,27])
a[(a>=5) & (a<=10)]

array([ 6,  9, 10])

In [16]:
def maxx(x,y):
    if x>=y:
        return x
    else:
        return y
    
pair_max=np.vectorize(maxx, otypes=[float])

a=np.array([5,7,9,8,6,4,5])
b=np.array([6,3,4,8,9,7,1])

pair_max(a,b)

array([6., 7., 9., 8., 9., 7., 5.])

In [17]:
arr=np.arange(9).reshape(3,3)
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [18]:
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [19]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [20]:
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [21]:
rand_arr=np.random.uniform(5,10,size=(5,3))
rand_arr

array([[6.36594339, 5.15527159, 6.77081101],
       [6.07077637, 5.97087747, 6.62253418],
       [5.06483081, 8.21839151, 9.990365  ],
       [6.23762958, 6.38922897, 7.02312023],
       [7.84232012, 8.71553007, 9.42502218]])

In [22]:
rand_arr=np.random.random((5,3))
np.set_printoptions(precision=3)
rand_arr[:4]

array([[0.126, 0.686, 0.499],
       [0.86 , 0.448, 0.46 ],
       [0.273, 0.34 , 0.842],
       [0.585, 0.516, 0.683]])

In [23]:
np.random.seed(100)
rand_arr=np.random.random([3,3])/1e3
np.set_printoptions(suppress=True, precision=6)
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

In [24]:
a=np.arange(15)
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [25]:
import sys
np.set_printoptions(threshold=sys.maxsize)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris=np.genfromtxt(url,delimiter=',',dtype='object')
names=('sepallength','sepalwidth','petallength','petalwidth','species')
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [27]:
iris_1d=np.genfromtxt(url,delimiter=',',dtype=None)
species=np.array([row[4] for row in iris_1d])
species[:5]

C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  """Entry point for launching an IPython kernel.


array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype='|S18')

In [28]:
iris_2d=np.array([row.tolist()[:4] for row in iris_1d])
iris_2d[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [29]:
sepallength=np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0] )
mu, med, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print(mu, med, sd)

5.843333333333334 5.8 0.8253012917851409


In [30]:
Smax, Smin = sepallength.max(), sepallength.min()
S=(sepallength - Smin)/sepallength.ptp()
print(S)

[0.222222 0.166667 0.111111 0.083333 0.194444 0.305556 0.083333 0.194444
 0.027778 0.166667 0.305556 0.138889 0.138889 0.       0.416667 0.388889
 0.305556 0.222222 0.388889 0.222222 0.305556 0.222222 0.083333 0.222222
 0.138889 0.194444 0.194444 0.25     0.25     0.111111 0.138889 0.305556
 0.25     0.333333 0.166667 0.194444 0.333333 0.166667 0.027778 0.222222
 0.194444 0.055556 0.027778 0.194444 0.222222 0.138889 0.222222 0.083333
 0.277778 0.194444 0.75     0.583333 0.722222 0.333333 0.611111 0.388889
 0.555556 0.166667 0.638889 0.25     0.194444 0.444444 0.472222 0.5
 0.361111 0.666667 0.361111 0.416667 0.527778 0.361111 0.444444 0.5
 0.555556 0.5      0.583333 0.638889 0.694444 0.666667 0.472222 0.388889
 0.333333 0.333333 0.416667 0.472222 0.305556 0.472222 0.666667 0.555556
 0.361111 0.333333 0.333333 0.5      0.416667 0.194444 0.361111 0.388889
 0.388889 0.527778 0.222222 0.388889 0.555556 0.416667 0.777778 0.555556
 0.611111 0.916667 0.166667 0.833333 0.666667 0.805556 0.6111

In [31]:
def softmax(x):
    e_x=np.exp(x-np.max(x))
    return e_x / e_x.sum(axis=0)
print(softmax(sepallength))

[0.00222  0.001817 0.001488 0.001346 0.002008 0.002996 0.001346 0.002008
 0.001102 0.001817 0.002996 0.001644 0.001644 0.000997 0.00447  0.004044
 0.002996 0.00222  0.004044 0.00222  0.002996 0.00222  0.001346 0.00222
 0.001644 0.002008 0.002008 0.002453 0.002453 0.001488 0.001644 0.002996
 0.002453 0.003311 0.001817 0.002008 0.003311 0.001817 0.001102 0.00222
 0.002008 0.001218 0.001102 0.002008 0.00222  0.001644 0.00222  0.001346
 0.002711 0.002008 0.01484  0.008144 0.013428 0.003311 0.009001 0.004044
 0.007369 0.001817 0.009947 0.002453 0.002008 0.00494  0.005459 0.006033
 0.003659 0.010994 0.003659 0.00447  0.006668 0.003659 0.00494  0.006033
 0.007369 0.006033 0.008144 0.009947 0.01215  0.010994 0.005459 0.004044
 0.003311 0.003311 0.00447  0.005459 0.002996 0.005459 0.010994 0.007369
 0.003659 0.003311 0.003311 0.006033 0.00447  0.002008 0.003659 0.004044
 0.004044 0.006668 0.00222  0.004044 0.007369 0.00447  0.016401 0.007369
 0.009001 0.02704  0.001817 0.020032 0.010994 0.01812

In [32]:
np.percentile(sepallength, q=[5,95])

array([4.6  , 7.255])

In [33]:
iris_2d=np.genfromtxt(url, delimiter=',', dtype='object')
np.random.seed(100)
iris_2d[np.random.randint(150,size=20), np.random.randint(4,size=20)]=np.nan
print(iris_2d[:10])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' nan b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]


In [34]:
iris_2d=np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150,size=20), np.random.randint(4,size=20)]=np.nan
print('Number of missing values:\n', np.isnan(iris_2d[:,0]).sum())
print('Position of missing values:\n', np.where(np.isnan(iris_2d[:,0])))

Number of missing values:
 5
Position of missing values:
 (array([ 38,  80, 106, 113, 121], dtype=int64),)


In [35]:
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
condition=(iris_2d[:,2]>1.5) & (iris_2d[:,0]<5.0)
iris_2d[condition]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [36]:
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
any_nan_in_row = np.array([~np.any(np.isnan(row)) for row in iris_2d])
iris_2d[any_nan_in_row][:5]

array([[4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [4.6, 3.4, 1.4, 0.3]])

In [37]:
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
np.corrcoef(iris[:,0], iris[:,2])[0,1]

0.8717541573048718

In [38]:
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
np.isnan(iris_2d).any()

False

In [39]:
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
iris_2d[np.isnan(iris_2d)]=0
iris_2d[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [40]:
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
species = np.array([row.tolist()[4] for row in iris])
np.unique(species, return_counts=True)

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
       dtype='|S15'), array([50, 50, 50], dtype=int64))

In [41]:
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
petal_length_bin=np.digitize(iris[:,2].astype('float'),[0,3,5,10])
label_map = {1:'small', 2:'medium', 3:'large', 4:np.nan}
petal_length_cat= [label_map[x] for x in petal_length_bin]
petal_length_cat[:4]

['small', 'small', 'small', 'small']

In [42]:
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = iris_2d[:,0].astype('float')
petallength = iris_2d[:,2].astype('float')
volume=(np.pi*petallength*(sepallength**2))/3
volume=volume[:,np.newaxis]
out = np.hstack([iris_2d,volume])
out[:4]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa',
        38.13265162927291],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa',
        35.200498485922445],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa', 30.0723720777127],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa',
        33.238050274980004]], dtype=object)

In [43]:
iris = np.genfromtxt(url, delimiter=',', dtype='object')
species=iris[:,4]
np.random.seed(100)
a=np.array(['iris-setosa','iris-versicolor','iris-virginica'])
species_out = np.random.choice(a,150,p=[0.5,0.25,0.25])

In [44]:
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
petal_len_setosa=iris[iris[:,4]==b'Iris-setosa',[2]].astype('float')
np.unique(np.sort(petal_len_setosa))[-2]

1.7

In [45]:
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
print(iris[iris[:,0].argsort()][:20])

[[b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'4.4' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'3.0' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.5' b'2.3' b'1.3' b'0.3' b'Iris-setosa']
 [b'4.6' b'3.6' b'1.0' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'4.6' b'3.2' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.3' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.9' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.1' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.9' b'2.4' b'3.3' b'1.0' b'Iris-versicolor']
 [b'4.9' b'2.5' b'4.5' b'1.7' b'Iris-virginica']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]


In [46]:
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
vals, counts = np.unique(iris[:,2], return_counts=True)
print(vals[np.argmax(counts)])

b'1.5'


In [47]:
iris = np.genfromtxt(url, delimiter=',', dtype='object')
np.argwhere(iris[:,3].astype(float)>1.0)[0]

array([50], dtype=int64)

In [48]:
np.random.seed(100)
a=np.random.uniform(1,50,20)
np.clip(a,a_min=10, a_max=30)

array([27.626842, 14.6401  , 21.801362, 30.      , 10.      , 10.      ,
       30.      , 30.      , 10.      , 29.179573, 30.      , 11.250904,
       10.081083, 10.      , 11.765177, 30.      , 30.      , 10.      ,
       30.      , 14.429614])

In [49]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)
print(a.argsort()[:5])

[ 4 13  5  8 17]


In [50]:
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
def counts_of_all_values_rowwise(arr2d):
    num_counts_array = [np.unique(row, return_counts=True) for row in arr2d]
    return ([[int(b[a==i]) if i in a else 0 for i in np.unique(arr2d)] for a,b in num_counts_array])
print(np.arange(1,11))
counts_of_all_values_rowwise(arr)

[ 1  2  3  4  5  6  7  8  9 10]


[[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
 [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
 [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
 [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
 [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
 [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]

In [51]:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])
array_of_arrays

arr_2d = np.concatenate(array_of_arrays)
arr_2d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
def one_hot_encodings(arr):
    uniqs = np.unique(arr)
    out=np.zeros((arr.shape[0], uniqs.shape[0]))
    for i,k in enumerate(arr):
        out[i,k-1]=1
    return out

one_hot_encodings(arr)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [53]:
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
np.random.seed(100)
species_small = np.sort(np.random.choice(species, size=20))
species_small
print([i for val in np.unique(species_small) for i, grp in enumerate(species_small[species_small==val])])

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5]


In [54]:
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
np.random.seed(100)
species_small = np.sort(np.random.choice(species, size=20))
species_small
output = [np.argwhere(np.unique(species_small) == s).tolist()[0][0] for val in np.unique(species_small) for s in species_small[species_small==val]]
print(output)

[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]


In [55]:
np.random.seed(10)
a = np.random.randint(20, size=10)
print(a.argsort().argsort())

[4 2 6 0 8 7 9 3 5 1]


In [56]:
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a.ravel().argsort().argsort().reshape(a.shape))

[[4 2 6 0 8]
 [7 9 3 5 1]]


In [57]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
np.amax(a,axis=1)

array([9, 8, 6, 3, 9])

In [58]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
np.apply_along_axis(lambda x: np.min(x)/np.max(x), arr=a, axis=1)

array([0.444444, 0.125   , 0.5     , 1.      , 0.111111])

In [59]:
np.random.seed(100)
a = np.random.randint(0, 5, 10)
out=np.full(a.shape[0], True)

unique_position=np.unique(a, return_index=True)[1]
out[unique_position]=False
out


array([False,  True, False,  True, False, False,  True,  True,  True,
        True])

In [60]:
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
numeric_column=iris[:,1].astype('float')
grouping_column = iris[:,4]
[[group_val, numeric_column[grouping_column==group_val].mean()] for group_val in np.unique(grouping_column)]

[[b'Iris-setosa', 3.418],
 [b'Iris-versicolor', 2.7700000000000005],
 [b'Iris-virginica', 2.974]]

In [61]:
from io import BytesIO
from PIL import Image
import PIL, requests
URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'
response = requests.get(URL)
I = Image.open(BytesIO(response.content))
I = I.resize([150,150])
arr=np.asarray(I)
im = PIL.Image.fromarray(np.uint8(arr))
Image.Image.show(im)

In [62]:
a=np.array([1,2,3,np.nan,5,6,7,np.nan])
a[~np.isnan(a)]

array([1., 2., 3., 5., 6., 7.])

In [63]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
dist = np.linalg.norm(a-b)
dist

6.708203932499369

In [64]:
a = np.array([1,3,7,1,2,6,0,1])
doublediff = np.diff(np.sign(np.diff(a)))
peak_locations = np.where(doublediff == -2)[0] +1
peak_locations

array([2, 5], dtype=int64)

In [65]:
a_2d = np.array([[3,3,3], [4,4,4], [5,5,5]])
b_1d = np.array([1,2,3])
print(a_2d - b_1d[:,None])

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [66]:
x = np.array([1,2,1,1,3,4,3,1,1,2,1,1,2])
n = 5
np.where(x==1)[0][n-1]

8

In [67]:
dt64=np.datetime64('2018-02-25 22:10:10')
from datetime import datetime
dt64.astype(datetime)

datetime.datetime(2018, 2, 25, 22, 10, 10)

In [68]:
np.random.seed(100)
Z = np.random.randint(10, size=10)
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n-1:]/n
moving_average(Z, n=3).round(2)

array([6.33, 6.  , 5.67, 4.67, 3.67, 2.  , 3.67, 3.  ])

In [69]:
length = 10
start = 5
step = 3

def seq(start, length, step):
    end = start + (step*length)
    return np.arange(start, end, step)

seq(start, length, step)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

In [70]:
dates = np.arange(np.datetime64('2018-02-01'), np.datetime64('2018-02-25'), 2)
filled_in = np.array([np.arange(date,(date+d)) for date, d in zip(dates, np.diff(dates))]).reshape(-1)
output=np.hstack([filled_in, dates[-1]])
output

array(['2018-02-01', '2018-02-02', '2018-02-03', '2018-02-04',
       '2018-02-05', '2018-02-06', '2018-02-07', '2018-02-08',
       '2018-02-09', '2018-02-10', '2018-02-11', '2018-02-12',
       '2018-02-13', '2018-02-14', '2018-02-15', '2018-02-16',
       '2018-02-17', '2018-02-18', '2018-02-19', '2018-02-20',
       '2018-02-21', '2018-02-22', '2018-02-23'], dtype='datetime64[D]')

In [71]:
arr = np.arange(15)
def gen_strides(a, stride_len=5, window_len=5):
    n_strides=((a.size-window_len)//stride_len)+1
    return np.array([a[s:(s+window_len)] for s in np.arange(0, n_strides*stride_len, stride_len)])
print(gen_strides(np.arange(15), stride_len=2, window_len=4))

[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]]
