In [2]:
#1
import numpy as np
import pandas as pd
print(pd.__version__)
print(pd.show_versions(as_json=True))

0.25.1
{'system': {'commit': None, 'python': '3.7.4.final.0', 'python-bits': 64, 'OS': 'Windows', 'OS-release': '10', 'machine': 'AMD64', 'processor': 'Intel64 Family 6 Model 142 Stepping 10, GenuineIntel', 'byteorder': 'little', 'LC_ALL': 'None', 'LANG': 'None', 'LOCALE': 'None.None'}, 'dependencies': {'pandas': '0.25.1', 'numpy': '1.16.5', 'pytz': '2019.3', 'dateutil': '2.8.0', 'pip': '19.2.3', 'setuptools': '41.4.0', 'Cython': '0.29.13', 'pytest': '5.2.1', 'hypothesis': None, 'sphinx': '2.2.0', 'blosc': None, 'feather': None, 'xlsxwriter': '1.2.1', 'lxml.etree': '4.4.1', 'html5lib': '1.0.1', 'pymysql': None, 'psycopg2': None, 'jinja2': '2.10.3', 'IPython': '7.8.0', 'pandas_datareader': '0.8.1', 'bs4': '4.8.0', 'bottleneck': '1.2.1', 'fastparquet': None, 'gcsfs': None, 'matplotlib': '3.1.1', 'numexpr': '2.7.0', 'odfpy': None, 'openpyxl': '3.0.0', 'pandas_gbq': None, 'pyarrow': None, 'pytables': None, 's3fs': None, 'scipy': '1.3.1', 'sqlalchemy': '1.3.9', 'tables': '3.5.2', 'xarray': 

In [3]:
#2
mylist = list('abcdefghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

ser1=pd.Series(mylist)
ser2=pd.Series(myarr)
ser3=pd.Series(mydict)
print(ser3.head())

a    0
b    1
c    2
d    3
e    4
dtype: int64


In [4]:
#3
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)

df = ser.to_frame().reset_index()
print(df.head())

  index  0
0     a  0
1     b  1
2     c  2
3     e  3
4     d  4


In [6]:
#4
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

df=pd.concat([ser1,ser2], axis=1)
print(df.head())

   0  1
0  a  0
1  b  1
2  c  2
3  e  3
4  d  4


In [7]:
#5
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))

ser1.name = 'alphabets'
ser1.head()

0    a
1    b
2    c
3    e
4    d
Name: alphabets, dtype: object

In [8]:
#6
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

ser1[~ser1.isin(ser2)]

0    1
1    2
2    3
dtype: int64

In [9]:
#7
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

ser_u=pd.Series(np.union1d(ser1, ser2))
ser_i=pd.Series(np.intersect1d(ser1,ser2))
ser_u[~ser_u.isin(ser_i)]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [10]:
#8
state = np.random.RandomState(100)
ser = pd.Series(state.normal(10,5,25))

np.percentile(ser,q=[0,25,50,75,100])

array([ 1.25117263,  7.70986507, 10.92259345, 13.36360403, 18.0949083 ])

In [11]:
#9
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
ser.value_counts()

e    7
h    6
b    5
g    3
a    3
f    3
d    2
c    1
dtype: int64

In [12]:
#10
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1,5,[12]))

print('Top 2 Freq:', ser.value_counts())
ser[~ser.isin(ser.value_counts().index[:2])]='Other'
ser

Top 2 Freq: 2    4
4    3
1    3
3    2
dtype: int64


0         2
1         4
2     Other
3     Other
4         4
5     Other
6         4
7         2
8         2
9     Other
10        2
11    Other
dtype: object

In [13]:
#11
ser = pd.Series(np.random.random(20))
print(ser.head())

pd.qcut(ser, q=[0,.10,.20,.3,.4,.5,.6,.7,.8,.9,1],
        labels = ['1st', '2nd', '3rd', '4th','5th','6th','7th','8th','9th','10th'])

0    0.759082
1    0.193852
2    0.390181
3    0.021313
4    0.561184
dtype: float64


0      9th
1      3rd
2      6th
3      1st
4      7th
5      2nd
6      5th
7      2nd
8      4th
9     10th
10     9th
11     8th
12     1st
13     5th
14     6th
15     4th
16     7th
17    10th
18     8th
19     3rd
dtype: category
Categories (10, object): [1st < 2nd < 3rd < 4th ... 7th < 8th < 9th < 10th]

In [14]:
#12
ser=pd.Series(np.random.randint(1,10,35))

df=pd.DataFrame(ser.values.reshape(7,5))
print(df)

   0  1  2  3  4
0  9  8  3  4  7
1  9  9  9  4  7
2  6  4  8  2  9
3  2  1  8  5  1
4  5  3  7  8  8
5  8  9  5  4  4
6  7  3  5  3  5


In [15]:
ser = pd.Series(np.random.randint(1,10,7))
ser

print(ser)
np.argwhere(ser%3==0)

0    8
1    9
2    5
3    4
4    2
5    7
6    8
dtype: int32


C:\Users\admin\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:56: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  return getattr(obj, method)(*args, **kwds)


array([[1]], dtype=int64)

In [16]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

ser.take(pos)

0     a
4     e
8     i
14    o
20    u
dtype: object

In [17]:
#15
ser1=pd.Series(range(5))
ser2=pd.Series(list('abcde'))

ser1.append(ser2)

df=pd.concat([ser1,ser2], axis=1)
print(df)

   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e


In [18]:
#16
ser1=pd.Series([10,9,6,5,3,1,12,8,13])
ser2=pd.Series([1,3,10,13])

[np.where(i==ser1)[0].tolist()[0] for i in ser2]

[5, 4, 0, 8]

In [19]:
#17
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

np.mean((truth-pred)**2)

0.5547423013843045

In [20]:
#18
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
ser.map(lambda x: x.title())

0     How
1      To
2    Kick
3    Ass?
dtype: object

In [21]:
#19
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
ser.map(lambda x: len(x))

0    3
1    2
2    4
3    4
dtype: int64

In [22]:
#20
ser = pd.Series([1,3,6,10,15,21,27,35])

print(ser.diff().tolist())
print(ser.diff().diff().tolist())

[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]
[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]


In [23]:
#21
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

from dateutil.parser import parse
ser.map(lambda x: parse(x))

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

In [24]:
#22
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

from dateutil.parser import parse
ser_ts=ser.map(lambda x: parse(x))

print('Date:', ser_ts.dt.day.tolist())
print('Week number:', ser_ts.dt.weekofyear.tolist())
print('Day number of year:', ser_ts.dt.dayofyear.tolist())
print('Day of week:', ser_ts.dt.weekday_name.tolist())

Date: [1, 2, 3, 4, 5, 6]
Week number: [53, 5, 9, 14, 19, 23]
Day number of year: [1, 33, 63, 94, 125, 157]
Day of week: ['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']


In [26]:
#23
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])

ser.map(lambda x: parse('04' + x))


0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]

In [27]:
#24
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])

from collections import Counter
mask = ser.map(lambda x: sum([Counter(x.lower()).get(i,0) for i in list('aeiou')])>=2)
ser[mask]

0     Apple
1    Orange
4     Money
dtype: object

In [28]:
#25
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])

import re
pattern = '[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'
mask=emails.map(lambda x:bool(re.match(pattern, x)))
emails[mask]

1    rameses@egypt.com
2            matt@t.co
3    narendra@modi.com
dtype: object

In [29]:
#26
fruit = pd.Series(np.random.choice(['apple', 'banna', 'carrot'], 10))
weights = pd.Series(np.linspace(1,10,10))

weights.groupby(fruit).mean()

apple     6.500000
banna     4.666667
carrot    5.000000
dtype: float64

In [30]:
#27
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

np.linalg.norm(p-q)

18.16590212458495

In [31]:
#28
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])

dd=np.diff(np.sign(np.diff(ser)))
peak_locs = np.where(dd==-2)[0] + 1
peak_locs

array([1, 5, 7], dtype=int64)

In [32]:
#29
my_str = 'dbc deb abed gade'

ser = pd.Series(list('dbc deb abed gade'))
freq=ser.value_counts()
print(freq)
least_freq = freq.dropna().index[-1]
''.join(ser.replace('', least_freq))

d    4
     3
e    3
b    3
a    2
g    1
c    1
dtype: int64


'dbc deb abed gade'

In [33]:
#30
ser = pd.Series(np.random.randint(1,10,10), pd.date_range('2000-01-01', periods=10, freq='W-SAT'))
ser

2000-01-01    9
2000-01-08    9
2000-01-15    8
2000-01-22    4
2000-01-29    7
2000-02-05    6
2000-02-12    2
2000-02-19    9
2000-02-26    7
2000-03-04    8
Freq: W-SAT, dtype: int32

In [34]:
#31
ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))

ser.resample('D').ffill()

2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     NaN
Freq: D, dtype: float64

In [35]:
#32
ser = pd.Series(np.arange(20) + np.random.normal(1,10,20))

autocorrelations = [ser.autocorr(i).round(2) for i in range(11)]
print(autocorrelations[1:])
print('Lag having highest correlation:', np.argmax(np.abs(autocorrelations[1:]))+1)

[0.3, -0.1, 0.1, 0.59, 0.03, -0.2, 0.16, 0.55, -0.01, -0.08]
Lag having highest correlation: 4


In [36]:
#33
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', chunksize=50)
df2=pd.DataFrame()
for chunk in df:
    df2 = df2.append(chunk.iloc[0,:])
    
print(df2.head())

      age       b  chas     crim     dis  indus  lstat  medv    nox  ptratio  \
0    65.2  396.90   0.0  0.00632  4.0900   2.31   4.98  24.0  0.538     15.3   
50   45.7  395.56   0.0  0.08873  6.8147   5.64  13.45  19.7  0.439     16.8   
100  79.9  394.76   0.0  0.14866  2.7778   8.56   9.42  27.5  0.520     20.9   
150  97.3  372.80   0.0  1.65660  1.6180  19.58  14.10  21.5  0.871     14.7   
200  13.9  384.30   0.0  0.01778  7.6534   1.47   4.45  32.9  0.403     17.0   

     rad     rm    tax    zn  
0    1.0  6.575  296.0  18.0  
50   4.0  5.963  243.0  21.0  
100  5.0  6.727  384.0   0.0  
150  5.0  6.122  403.0   0.0  
200  3.0  7.135  402.0  95.0  


In [38]:
#34
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', 
                 converters={'medv': lambda x: 'High' if float(x) > 25 else 'Low'})
print(df.head())

      crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98   Low  
1  396.90   9.14   Low  
2  392.83   4.03  High  
3  394.63   2.94  High  
4  396.90   5.33  High  


In [40]:
#35
L=pd.Series(range(15))

def gen_strides(a, stride_len=5, window_len=5):
    n_strides = ((a.size-window_len)//stride_len)+1
    return np.array([a[s:(s+window_len)] for s in np.arange(0, a.size, stride_len)[:n_strides]])

gen_strides(L, stride_len=2, window_len=4)

array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13]], dtype=int64)

In [41]:
#36
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', usecols=['crim', 'medv'])
print(df.head())

      crim  medv
0  0.00632  24.0
1  0.02731  21.6
2  0.02729  34.7
3  0.03237  33.4
4  0.06905  36.2


In [42]:
#37
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

print(df.shape)
print(df.dtypes)
print(df.get_dtype_counts())
print(df.dtypes.value_counts())

df_stats = df.describe()
df_arr = df.values
df_list = df.values.tolist()

(93, 27)
Manufacturer           object
Model                  object
Type                   object
Min.Price             float64
Price                 float64
Max.Price             float64
MPG.city              float64
MPG.highway           float64
AirBags                object
DriveTrain             object
Cylinders              object
EngineSize            float64
Horsepower            float64
RPM                   float64
Rev.per.mile          float64
Man.trans.avail        object
Fuel.tank.capacity    float64
Passengers            float64
Length                float64
Wheelbase             float64
Width                 float64
Turn.circle           float64
Rear.seat.room        float64
Luggage.room          float64
Weight                float64
Origin                 object
Make                   object
dtype: object
float64    18
object      9
dtype: int64
float64    18
object      9
dtype: int64


C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: `get_dtype_counts` has been deprecated and will be removed in a future version. For DataFrames use `.dtypes.value_counts()
  


In [43]:
#38
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df.loc[df.Price == np.max(df.Price), ['Manufacturer', 'Model', 'Type']]

row, col = np.where(df.values == np.max(df.Price))

df.iat[row[0], col[0]]
df.iloc[row[0], col[0]]

df.at[row[0], 'Price']
df.get_value(row[0], 'Price')

C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: FutureWarning: get_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  if sys.path[0] == '':


61.9

In [46]:
#39
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df.columns.values[2] = 'CarType'

print(df.columns)

Index(['Manufacturer', 'Model', 'CarType', 'Min.Price', 'Price', 'Max.Price',
       'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile', 'Man.trans.avail',
       'Fuel.tank.capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn.circle', 'Rear.seat.room', 'Luggage.room', 'Weight', 'Origin',
       'Make'],
      dtype='object')


In [47]:
#40
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df.isnull().values.any()

True

In [48]:
#41
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

n_missings_each_col = df.apply(lambda x:x.isnull().sum())
n_missings_each_col.argmax()

C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: 
The current behaviour of 'Series.argmax' is deprecated, use 'idxmax'
instead.
The behavior of 'argmax' will be corrected to return the positional
maximum in the future. For now, use 'series.values.argmax' or
'np.argmax(np.array(values))' to get the position of the maximum
row.
  after removing the cwd from sys.path.


'Luggage.room'

In [49]:
#42
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df_out = df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(lambda x:x.fillna(x.mean()))
print(df_out.head())

   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


In [50]:
#43
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

d={'Min.Price': np.nanmean, 'Max.Price': np.nanmedian}
df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(lambda x, d: x.fillna(d[x.name](x)), args=(d,))


In [51]:
#44

df=pd.DataFrame(np.arange(20).reshape(-1,5), columns=list('abcde'))

type(df[['a']])
type(df.loc[:,['a']])
type(df.iloc[:,[0]])

pandas.core.frame.DataFrame

In [3]:
#45

df = pd.DataFrame(np.arange(20).reshape(-1,5), columns=list('abcde'))

df[list('cbade')]


c   b   a   d   e
0   2   1   0   3   4
1   7   6   5   8   9
2  12  11  10  13  14
3  17  16  15  18  19

In [4]:
#46

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

pd.set_option('display.max_columns', 10)
pd.set_option('display.max_rows',10)

In [5]:
#47

df = pd.DataFrame(np.random.random(4)**10, columns=['random'])

df.round(4)

random
0  0.0003
1  0.2645
2  0.0001
3  0.7376

In [6]:
#48

df = pd.DataFrame(np.random.random(4), columns=['random'])

out=df.style.format({
    'random':'{0:.2%}'.format,
})

out

In [9]:
#49

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

print(df.iloc[::20, :][['Manufacturer', 'Model', 'Type']])

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [10]:
#50

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])

df[['Manufacturer', 'Model', 'Type']]=df[['Manufacturer','Model','Type']].fillna('missing')
df.index = df.Manufacturer+'_'+df.Model+'_'+df.Type
print(df.index.is_unique)

True


In [11]:
#51

df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))

n=5
df['a'].argsort()[::-1][n]

3

In [12]:
#52

ser = pd.Series(np.random.randint(1,100,15))

print('ser:', ser.tolist(), 'mean:', round(ser.mean()))
np.argwhere(ser>ser.mean())[1]

ser: [8, 79, 84, 16, 40, 62, 60, 22, 27, 92, 68, 75, 74, 38, 32] mean: 52


C:\Users\admin\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:56: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  return getattr(obj, method)(*args, **kwds)


array([2], dtype=int64)

In [13]:
#53

df = pd.DataFrame(np.random.randint(10,40,60).reshape(-1,4))

rowsums = df.apply(np.sum, axis=1)

last_two_rows=df.iloc[np.where(rowsums>100)[0][-2:],:]

In [14]:
#54

ser = pd.Series(np.logspace(-2,2,30))

def cap_outliers(ser, low_perc, high_perc):
    low, high = ser.quantile([low_perc, high_perc])
    print(low_perc, '%ile:',low,'I',high_perc, '%ile:',high)
    ser[ser<low]=low
    ser[ser>high]=high
    return(ser)

capped_ser = cap_outliers(ser, .05, .95)

0.05 %ile: 0.016049294076965887 I 0.95 %ile: 63.876672220183934


In [18]:
#55

df = pd.DataFrame(np.random.randint(-20,50,100).reshape(10,-1))
print(df)

arr=df[df>0].values.flatten()
arr_qualified=arr[~np.isnan(arr)]

n=int(np.floor(arr_qualified.shape[0]**.5))

top_indexes = np.argsort(arr_qualified)[::-1]
output = np.take(arr_qualified, sorted(top_indexes[:n**2])).reshape(n,-1)
print(output)

    0   1   2   3   4   5   6   7   8   9
0  12 -11  39  28  47  42  19  35  38 -12
1  21 -14  13 -14  45 -11  49 -19  23  28
2   7  25  23  -5  39  47   0  39  12 -10
3  45 -15 -12  44  45 -10  -7 -14  -4  48
4  21  30  20  29  36   6   3  44   4  -9
5  46   9  31  29   4  34  -1  27  36  25
6 -16   2  -6  20   2  17  21  37   2  38
7 -19  20  -3  46  43 -14  24  44  20  22
8  17  14 -19  -3  35  33  -1  48 -19 -10
9   8  23  22  -1   3  10  22  16  23  42
[[12. 39. 28. 47. 42. 19. 35. 38.]
 [21. 13. 45. 49. 23. 28.  7. 25.]
 [23. 39. 47. 39. 12. 45. 44. 45.]
 [48. 21. 30. 20. 29. 36. 44. 46.]
 [ 9. 31. 29. 34. 27. 36. 25. 20.]
 [17. 21. 37. 38. 20. 46. 43. 24.]
 [44. 20. 22. 17. 14. 35. 33. 48.]
 [ 8. 23. 22. 10. 22. 16. 23. 42.]]


In [20]:
#56

df = pd.DataFrame(np.arange(25).reshape(5,-1))

def swap_rows(df,i1,i2):
    a, b = df.iloc[i1,:].copy(),df.iloc[i2,:].copy()
    df.iloc[i1,:], df.iloc[i2,:] = b, a
    return df

print(swap_rows(df,1,2))

    0   1   2   3   4
0   0   1   2   3   4
1  10  11  12  13  14
2   5   6   7   8   9
3  15  16  17  18  19
4  20  21  22  23  24


In [21]:
#57

df = pd.DataFrame(np.arange(25).reshape(5,-1))

df.iloc[::-1,:]

0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4

In [22]:
#58

df = pd.DataFrame(np.arange(25).reshape(5,-1), columns=list('abcde'))

df_onehot = pd.concat([pd.get_dummies(df['a']),df[list('bcde')]], axis=1)
print(df_onehot)

   0  5  10  15  20   b   c   d   e
0  1  0   0   0   0   1   2   3   4
1  0  1   0   0   0   6   7   8   9
2  0  0   1   0   0  11  12  13  14
3  0  0   0   1   0  16  17  18  19
4  0  0   0   0   1  21  22  23  24


In [23]:
#59

df = pd.DataFrame(np.random.randint(1,100,40).reshape(10,-1))

print('Column with highest row maxes:', df.apply(np.argmax, axis=1).value_counts().index[0])

Column with highest row maxes: 1


C:\Users\admin\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:56: FutureWarning: 
The current behaviour of 'Series.argmax' is deprecated, use 'idxmax'
instead.
The behavior of 'argmax' will be corrected to return the positional
maximum in the future. For now, use 'series.values.argmax' or
'np.argmax(np.array(values))' to get the position of the maximum
row.
  return getattr(obj, method)(*args, **kwds)


In [25]:
#60

df = pd.DataFrame(np.random.randint(1,100,40).reshape(10,-1), columns=list('pqrs'), index=list('abcdefghij'))

nearest_rows=[]
nearest_distance=[]

for i, row in df.iterrows():
    curr=row
    rest = df.drop(i)
    e_dists={}
    for j, contestant in rest.iterrows():
        e_dists.update({j: round(np.linalg.norm(curr.values-contestant.values))})
    nearest_rows.append(max(e_dists, key=e_dists.get))
    nearest_distance.append(max(e_dists.values()))
    
df['nearest_row']=nearest_rows
df['dist']=nearest_distance

In [26]:
#61

df = pd.DataFrame(np.random.randint(1,100,80).reshape(8,-1), columns=list('pqrstuvwxy'), index=list('abcdefgh'))
df

abs_corrmat = np.abs(df.corr())
max_corr = abs_corrmat.apply(lambda x: sorted(x)[-2])
print('Maximum Correlation possible for each column:', np.round(max_corr.tolist(),2))

Maximum Correlation possible for each column: [0.76 0.32 0.67 0.81 0.67 0.57 0.76 0.58 0.76 0.81]


In [27]:
#62

df = pd.DataFrame(np.random.randint(1,100,80).reshape(8,-1))

min_by_max = df.apply(lambda x: np.min(x)/np.max(x), axis=1)

In [28]:
#63

df = pd.DataFrame(np.random.randint(1,100,80).reshape(8,-1))

out=df.apply(lambda x:x.sort_values().unique()[-2], axis=1)
df['penultimate']=out
print(df)

    0   1   2   3   4  ...   6   7   8   9  penultimate
0  18  96  96  35  29  ...  41  70  69  54           70
1  35  83  41  82  93  ...  64  21  18  66           93
2  85  86  90  59  44  ...  34   4  66  35           90
3  15  70  60   1   9  ...  58  92  73  96           92
4  93  71  84  26  90  ...  13  93  86  65           90
5  63  65  29  39  88  ...  43  37   5  77           77
6  62  93  12  23   5  ...  92  92  86  84           92
7  31  13  25  86  73  ...  39  92  77   6           86

[8 rows x 11 columns]


In [29]:
#64
df = pd.DataFrame(np.random.randint(1,100,80).reshape(8,-1))

out1=df.apply(lambda x:((x-x.mean())/x.std()).round(2))
print('Solution Q1\n',out1)

Solution Q1
       0     1     2     3     4     5     6     7     8     9
0 -0.51  0.63 -1.42  0.47  0.14  1.31 -0.32  0.87 -1.08  0.18
1 -1.13  0.78  0.71  1.76 -1.05  0.39 -0.09 -1.02 -1.08  0.23
2  0.54  0.07 -1.42 -0.10  0.99 -0.08  1.22  0.01  1.16 -0.17
3  1.31 -1.42  0.03 -0.71 -1.69 -0.36 -0.52 -0.12 -0.83  0.18
4 -1.43  1.27  0.84  0.33 -0.33  1.31 -0.83  1.67 -0.16  1.05
5  0.76 -0.63  0.11  0.18  0.22 -0.11  1.46 -0.47  1.36 -1.09
6 -0.37 -1.27  1.31 -1.72  0.39 -1.57 -1.43 -1.40 -0.21 -1.70
7  0.83  0.57 -0.14 -0.21  1.33 -0.89  0.52  0.46  0.84  1.30


In [30]:
#65
df=pd.DataFrame(np.random.randint(1,100,80).reshape(8,-1))

[df.iloc[i].corr(df.iloc[i+1]).round(2) for i in range(df.shape[0])[:-1]]

[-0.01, 0.53, 0.02, -0.73, 0.28, 0.23, -0.06]

In [31]:
#66
df = pd.DataFrame(np.random.randint(1,100,100).reshape(10,-1))

for i in range(df.shape[0]):
    df.iat[i,i]=0
    df.iat[df.shape[0]-i-1,i]=0

In [32]:
#67
df = pd.DataFrame({'col1':['apple', 'banana', 'orange']*3,
                  'col2': np.random.rand(9),
                  'col3': np.random.randint(0,15,9)})

df_grouped = df.groupby(['col1'])

df_grouped.get_group('apple')

col1      col2  col3
0  apple  0.304251     3
3  apple  0.929410     0
6  apple  0.296871     0

In [33]:
#68
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'taste': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})

df_grpd = df['taste'].groupby(df.fruit)
df_grpd.get_group('banana').sort_values().iloc[-2]

0.5296482835945538

In [34]:
#69
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})
out = df.groupby('fruit', as_index=False)['price'].mean()
print(out)

    fruit      price
0   apple   6.000000
1  banana  10.666667
2  orange   7.333333


In [37]:
#70
df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})

pd.merge(df1, df2, how='inner', left_on=['fruit', 'weight'], right_on=['pazham', 'pounds'], suffixes=['_left', '_right'])

KeyError: 'pounds'

In [38]:
#71
df1 = pd.DataFrame({'fruit': ['apple', 'orange', 'banana'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.arange(9)})

df2 = pd.DataFrame({'fruit': ['apple', 'orange', 'pine'] * 2,
                    'weight': ['high', 'medium'] * 3,
                    'price': np.arange(6)})

print(df1[~df1.isin(df2).all(1)])

    fruit  weight  price
2  banana     low      2
3   apple    high      3
4  orange  medium      4
5  banana     low      5
6   apple    high      6
7  orange  medium      7
8  banana     low      8


In [39]:
#72
df = pd.DataFrame({'fruit1': np.random.choice(['apple', 'orange', 'banana'], 10),
                    'fruit2': np.random.choice(['apple', 'orange', 'banana'], 10)})

np.where(df.fruit1 == df.fruit2)

(array([1, 2, 3], dtype=int64),)

In [40]:
#73
df=pd.DataFrame(np.random.randint(1,100,20).reshape(-1,4),columns = list('abcd'))

df['a_lag1']=df['a'].shift(1)
df['b_lead1']=df['b'].shift(-1)
print(df)

    a   b   c   d  a_lag1  b_lead1
0  37   9   3  81     NaN     81.0
1  21  81  15  95    37.0     59.0
2  43  59   4  99    21.0     82.0
3  82  82  23  38    43.0     73.0
4  83  73  69  61    82.0      NaN


In [41]:
#74
df = pd.DataFrame(np.random.randint(1, 10, 20).reshape(-1, 4), columns = list('abcd'))

pd.value_counts(df.values.ravel())

8    4
2    4
9    3
6    2
5    2
3    2
1    2
4    1
dtype: int64

In [42]:
#75
df = pd.DataFrame(["STD, City    State",
"33, Kolkata    West Bengal",
"44, Chennai    Tamil Nadu",
"40, Hyderabad    Telengana",
"80, Bangalore    Karnataka"], columns=['row'])

df_out = df.row.str.split(',|\t', expand=True)

new_header = df_out.iloc[0]
df_out = df_out[1:]
df_out.columns = new_header
print(df_out)

0 STD            City    State
1  33   Kolkata    West Bengal
2  44    Chennai    Tamil Nadu
3  40   Hyderabad    Telengana
4  80   Bangalore    Karnataka
