Q1

In [1]:
import pandas as pd
print(pd.__version__)

0.24.2


Q2

In [3]:
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

In [5]:
pd.ser1 = pd.Series(mylist)
ser2 = pd.Series(myarr)
ser3 = pd.Series(mydict)
print(ser3.head())

a    0
b    1
c    2
e    3
d    4
dtype: int64


Q3

In [6]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)

In [8]:
df = ser.to_frame().reset_index()
print(df.head())

  index  0
0     a  0
1     b  1
2     c  2
3     e  3
4     d  4


Q4

In [9]:
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

In [13]:
df = pd.concat([ser1,ser2],axis=1)

df.head()

0  1
0  a  0
1  b  1
2  c  2
3  e  3
4  d  4

Q5

In [15]:
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser.name = 'alphabets'
ser.head()

0    a
1    b
2    c
3    e
4    d
Name: alphabets, dtype: object

Q6

In [16]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

ser1[~ser1.isin(ser2)]

0    1
1    2
2    3
dtype: int64

Q7

In [17]:
ser_u = pd.Series(np.union1d(ser1, ser2)) 
ser_i = pd.Series(np.intersect1d(ser1, ser2)) 
ser_u[~ser_u.isin(ser_i)]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

Q8

In [22]:
state = np.random.RandomState(100)
ser = pd.Series(state.normal(10, 5, 25))

pd.Series.quantile(ser, q = [0, .25, .50, .75, 1.00])

0.00     1.251173
0.25     7.709865
0.50    10.922593
0.75    13.363604
1.00    18.094908
dtype: float64

Q9

In [23]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

In [24]:
ser.head()

0    b
1    b
2    e
3    b
4    c
dtype: object

In [26]:
ser.value_counts()

b    10
a     5
c     4
e     3
d     3
h     3
g     2
dtype: int64

Q10

In [39]:
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))

In [40]:
print("Top 2 Freq : \n", ser.value_counts())
ser[~ser.isin(ser.value_counts().index[:2])] = 'Other'
ser

Top 2 Freq : 
 1    4
3    3
2    3
4    2
dtype: int64


0     Other
1     Other
2         1
3         1
4         1
5         3
6         3
7         3
8     Other
9     Other
10        1
11    Other
dtype: object

Q11

In [41]:
ser = pd.Series(np.random.random(20))
print(ser.head())

0    0.702472
1    0.088592
2    0.274942
3    0.626807
4    0.126795
dtype: float64


In [42]:
pd.qcut(ser, q=[0,.10, .20, .3, .4, .5, .6, .7, .8, .9, 1],
       labels=['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th']).head()

0    8th
1    2nd
2    4th
3    6th
4    2nd
dtype: category
Categories (10, object): [1st < 2nd < 3rd < 4th ... 7th < 8th < 9th < 10th]

Q12

In [43]:
ser = pd.Series(np.random.randint(1, 10, 35))

In [45]:
pd.DataFrame(ser.values.reshape(7,5))

0  1  2  3  4
0  7  4  7  9  9
1  5  5  8  7  5
2  1  3  5  2  3
3  8  9  4  1  2
4  2  5  2  2  8
5  6  6  8  6  9
6  1  1  6  2  1

Q13

In [46]:
ser = pd.Series(np.random.randint(1, 10, 7))

In [48]:
np.argwhere(ser % 3 == 0)

C:\Users\dhxog\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:56: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  return getattr(obj, method)(*args, **kwds)


array([[0],
       [1],
       [2],
       [6]], dtype=int64)

Q14

In [49]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

In [52]:
ser.take(pos)

0     a
4     e
8     i
14    o
20    u
dtype: object

Q15

In [53]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

In [60]:
print(ser1.append(ser2))

df = pd.concat([ser1, ser2], axis = 1)
print(df)

0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
4    e
dtype: object
   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e


Q16

In [61]:
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

In [66]:
[np.where(i == ser1)[0].tolist()[0] for i in ser2]

[5, 4, 0, 8]

Q17

In [2]:
import numpy as np

In [5]:
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

In [10]:
st = np.zeros(len(truth))
for i in range(len(truth)):
    st[i] = (truth[i]-pred[i])**2

se = np.sum(st)/len(truth)
print(se)

print(np.mean((truth-pred)**2))

0.4165930140967659
0.416593014096766


Q18

In [11]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

In [16]:
[s.capitalize() for s in ser]

['How', 'To', 'Kick', 'Ass?']

Q19

In [17]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

In [18]:
ser.map(lambda x: len(x))

0    3
1    2
2    4
3    4
dtype: int64

Q20

In [19]:
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

In [21]:
print(ser.diff().tolist())
print(ser.diff().diff().tolist())

[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]
[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]


Q21

In [22]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

In [26]:
pd.to_datetime(ser)

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

Q22

In [27]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

In [28]:
from dateutil.parser import parse
ser_ts = ser.map(lambda x: parse(x))

In [30]:
print("Date:", ser_ts.dt.day.tolist())
print("Week number:", ser_ts.dt.weekofyear.tolist())
print("Day of year:", ser_ts.dt.dayofyear.tolist())
print("Day of week:",ser_ts.dt.weekday_name.tolist())

Date: [1, 2, 3, 4, 5, 6]
Week number: [53, 5, 9, 14, 19, 23]
Day of year: [1, 33, 63, 94, 125, 157]
Day of week: ['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']


Q23

In [31]:
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])

In [33]:
ser.map(lambda x:parse('04'+x))

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]

Q24

In [34]:
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])

In [35]:
from collections import Counter
mask = ser.map(lambda x: sum([Counter(x.lower()).get(i, 0) for i in list('aeiou')]) >= 2)
ser[mask]

0     Apple
1    Orange
4     Money
dtype: object

Q25

In [36]:
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'

In [39]:
import re
emails.str.findall(pattern, flags=re.IGNORECASE)

0                     []
1    [rameses@egypt.com]
2            [matt@t.co]
3    [narendra@modi.com]
dtype: object

Q26

In [41]:
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
print(weights.tolist())
print(fruit.tolist())

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['banana', 'apple', 'apple', 'banana', 'apple', 'apple', 'carrot', 'banana', 'apple', 'carrot']


In [44]:
weights.groupby(fruit).mean()


apple     5.000000
banana    4.333333
carrot    8.500000
dtype: float64

Q27

In [45]:
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

In [47]:
sum((p-q)**2)**.5

18.16590212458495

Q28

In [3]:
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])

dd = np.diff(np.sign(np.diff(ser)))
peak_locs = np.where(dd == -2)[0] + 1
peak_locs

array([1, 5, 7], dtype=int64)

Q29

In [4]:
my_str = 'dbc deb abed gade'

In [8]:
ser = pd.Series(list('dbc deb abed gade'))
freq = ser.value_counts()
print(freq)
least_freq = freq.dropna().index[-1]
"".join(ser.replace(' ', least_freq))

d    4
b    3
     3
e    3
a    2
g    1
c    1
dtype: int64


'dbccdebcabedcgade'

Q30

In [19]:
ser = pd.Series(np.random.randint(1,10,10), pd.date_range('2000-01-01', periods=10, freq='W-SAT'))
ser

2000-01-01    3
2000-01-08    9
2000-01-15    4
2000-01-22    8
2000-01-29    8
2000-02-05    6
2000-02-12    4
2000-02-19    3
2000-02-26    6
2000-03-04    3
Freq: W-SAT, dtype: int32

Q31

In [20]:
ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
print(ser)

2000-01-01     1.0
2000-01-03    10.0
2000-01-06     3.0
2000-01-08     NaN
dtype: float64


In [21]:
ser.resample('D').ffill()

2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     NaN
Freq: D, dtype: float64

Q32

In [22]:
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))

In [23]:
autocorrelations = [ser.autocorr(i).round(2) for i in range(11)]
print(autocorrelations[1:])
print('Lag having highest correlation: ', np.argmax(np.abs(autocorrelations[1:]))+1)


[-0.1, 0.0, 0.12, 0.14, 0.16, 0.21, -0.1, -0.17, 0.32, -0.39]
Lag having highest correlation:  10


Q33

In [24]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', chunksize=50)
df2 = pd.DataFrame()
for chunk in df:
    df2 = df2.append(chunk.iloc[0,:])

In [26]:
qprint(df2.head())

      age       b  chas     crim     dis  indus  lstat  medv    nox  ptratio  \
0    65.2  396.90   0.0  0.00632  4.0900   2.31   4.98  24.0  0.538     15.3   
50   45.7  395.56   0.0  0.08873  6.8147   5.64  13.45  19.7  0.439     16.8   
100  79.9  394.76   0.0  0.14866  2.7778   8.56   9.42  27.5  0.520     20.9   
150  97.3  372.80   0.0  1.65660  1.6180  19.58  14.10  21.5  0.871     14.7   
200  13.9  384.30   0.0  0.01778  7.6534   1.47   4.45  32.9  0.403     17.0   

     rad     rm    tax    zn  
0    1.0  6.575  296.0  18.0  
50   4.0  5.963  243.0  21.0  
100  5.0  6.727  384.0   0.0  
150  5.0  6.122  403.0   0.0  
200  3.0  7.135  402.0  95.0  


Q34

In [35]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', 
                 converters={'medv': lambda x: 'High' if float(x) > 25 else 'Low'})

In [36]:
df.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98   Low  
1  396.90   9.14   Low  
2  392.83   4.03  High  
3  394.63   2.94  High  
4  396.90   5.33  High

Q35

In [37]:
L = pd.Series(range(15))

In [38]:
def gen_strides(a, stride_len=5, window_len=5):
    n_strides = ((a.size-window_len)//stride_len) + 1
    return np.array([a[s:(s+window_len)] for s in np.arange(0, a.size, stride_len)[:n_strides]])

gen_strides(L, stride_len=2, window_len=4)

array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13]], dtype=int64)

Q36

In [42]:
df2[['crim','medv']]

crim  medv
0     0.00632  24.0
50    0.08873  19.7
100   0.14866  27.5
150   1.65660  21.5
200   0.01778  32.9
250   0.14030  24.4
300   0.04417  24.8
350   0.06211  22.9
400  25.04610   5.6
450   6.71772  13.4
500   0.22438  16.8

Q37

In [43]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [45]:
print(df.shape)

(93, 27)


In [47]:
print(df.get_dtype_counts())
print(df.dtypes.value_counts())

float64    18
object      9
dtype: int64
float64    18
object      9
dtype: int64


In [48]:
df_stats = df.describe()

In [49]:
df_arr = df.values

In [50]:
df_list = df.values.tolist()

Q38

In [51]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [58]:
df[df['Price']==df['Price'].max()][['Manufacturer', 'Model','Type']]

Manufacturer Model     Type
58  Mercedes-Benz  300E  Midsize

In [59]:
row, col = np.where(df.values == np.max(df.Price))

In [60]:
df.iat[row[0], col[0]]
df.iloc[row[0], col[0]]

61.9

Q39

In [61]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df.columns)

Index(['Manufacturer', 'Model', 'Type', 'Min.Price', 'Price', 'Max.Price',
       'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile', 'Man.trans.avail',
       'Fuel.tank.capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn.circle', 'Rear.seat.room', 'Luggage.room', 'Weight', 'Origin',
       'Make'],
      dtype='object')


In [63]:
df = df.rename(columns = {'Type':'CarType'})

In [64]:
df.columns = df.columns.map(lambda x: x.replace('.', '_'))
print(df.columns)

Index(['Manufacturer', 'Model', 'CarType', 'Min_Price', 'Price', 'Max_Price',
       'MPG_city', 'MPG_highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev_per_mile', 'Man_trans_avail',
       'Fuel_tank_capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn_circle', 'Rear_seat_room', 'Luggage_room', 'Weight', 'Origin',
       'Make'],
      dtype='object')


Q40

In [66]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [69]:
df.isnull().values.any()

True

Q41

In [70]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [73]:
n_missings_each_col = df.apply(lambda x: x.isnull().sum())
n_missings_each_col.argmax()

C:\Users\dhxog\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: 
The current behaviour of 'Series.argmax' is deprecated, use 'idxmax'
instead.
The behavior of 'argmax' will be corrected to return the positional
maximum in the future. For now, use 'series.values.argmax' or
'np.argmax(np.array(values))' to get the position of the maximum
row.
  


'Luggage.room'

Q42

In [74]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [84]:
df_out = df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(lambda x: x.fillna(x.mean()))
print(df_out.head())

   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


Q43

In [85]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [89]:
d = {'Min.Price': np.nanmean, 'Max.Price': np.nanmedian}
df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(lambda x, d: x.fillna(d[x.name](x)), args=(d, ))

In [90]:
df.head()

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small  12.900000   15.9      18.80      25.0   
1          NaN   Legend  Midsize  29.200000   33.9      38.70      18.0   
2         Audi       90  Compact  25.900000   29.1      32.30      20.0   
3         Audi      100  Midsize  17.118605   37.7      44.60      19.0   
4          BMW     535i  Midsize  17.118605   30.0      19.15      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                None      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   

    Origin           Make  
0  non-USA  Acura Integra  
1  non-USA   Acura Legend  
2  non-USA        Audi 90  
3  non-USA       Audi 100  
4  non-USA       BMW 535i  

[5 rows x 27 columns]

Q44

In [91]:
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

In [93]:
type(df['a'])

pandas.core.series.Series

In [95]:
type(df.loc[:, ['a']])

pandas.core.frame.DataFrame

In [96]:
type(df.iloc[:, [0]])

pandas.core.frame.DataFrame

Q45

In [98]:
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))


df[list('cbade')]


def switch_columns(df, col1=None, col2=None):
    colnames = df.columns.tolist()
    i1, i2 = colnames.index(col1), colnames.index(col2)
    colnames[i2], colnames[i1] = colnames[i1], colnames[i2]
    return df[colnames]

df1 = switch_columns(df, 'a', 'c')

df[sorted(df.columns)]

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

Q46

In [99]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [100]:
pd.set_option('display.max_columns', 10)
pd.set_option('display.max_rows', 10)

In [101]:
pd.describe_option()

compute.use_bottleneck : bool
    Use the bottleneck library to accelerate if it is installed,
    the default is True
    Valid values: False,True
    [default: True] [currently: True]

compute.use_numexpr : bool
    Use the numexpr library to accelerate computation if it is installed,
    the default is True
    Valid values: False,True
    [default: True] [currently: True]

display.chop_threshold : float or None
    if set to a float value, all float values smaller then the given threshold
    will be displayed as exactly 0 by repr and friends.
    [default: None] [currently: None]

display.colheader_justify : 'left'/'right'
    Controls the justification of column headers. used by DataFrameFormatter.
    [default: right] [currently: right]

display.column_space No description available.
    [default: 12] [currently: 12]

display.date_dayfirst : boolean
    When True, prints and parses dates with the day first, eg 20/01/2005
    [default: False] [currently: False]

display.date_year

Q47

In [102]:
df = pd.DataFrame(np.random.random(4)**10, columns=['random'])
df

random
0  4.180306e-01
1  1.660915e-02
2  2.845563e-08
3  8.745938e-07

In [103]:
df.round(4)

random
0  0.4180
1  0.0166
2  0.0000
3  0.0000

Q48

In [104]:
df = pd.DataFrame(np.random.random(4), columns=['random'])
df

random
0  0.980927
1  0.329166
2  0.871817
3  0.313942

In [107]:
df = pd.DataFrame(np.random.random(4), columns=['random'])
df

In [109]:
out = df.style.format({
    'random': '{0:.2%}'.format,
})

In [110]:
out

Q49

In [111]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [117]:
df.iloc[::20,:][['Manufacturer', 'Model', 'Type']]

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

Q50

In [118]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])

In [119]:
df[['Manufacturer', 'Model', 'Type']] = df[['Manufacturer', 'Model', 'Type']].fillna('missing')
df.index = df.Manufacturer + '_' + df.Model + '_' + df.Type
print(df.index.is_unique)

True


Q51

In [120]:
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))

In [127]:
df['a'].argsort()[::-1][5]

9

Q52

In [128]:
ser = pd.Series(np.random.randint(1, 100, 15))

In [132]:
print('ser: ', ser.tolist(), 'mean: ', round(ser.mean()))
np.argwhere(ser > ser.mean())[1]

ser:  [45, 18, 76, 28, 24, 96, 58, 16, 35, 41, 88, 88, 41, 59, 1] mean:  48


C:\Users\dhxog\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:56: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  return getattr(obj, method)(*args, **kwds)


array([5], dtype=int64)

Q53

In [133]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [134]:
df

0   1   2   3
0   12  39  26  32
1   24  34  12  33
2   27  14  12  13
3   18  18  33  35
4   14  14  31  27
..  ..  ..  ..  ..
10  15  39  16  27
11  27  14  10  38
12  21  32  39  19
13  21  22  15  15
14  34  20  36  39

[15 rows x 4 columns]

In [136]:
rowsums = df.apply(np.sum, axis=1)

In [138]:
 df.iloc[np.where(rowsums > 100)[0][-2:], :]

0   1   2   3
12  21  32  39  19
14  34  20  36  39

Q54

In [141]:
ser = pd.Series(np.logspace(-2, 2, 30))

In [147]:
def cap_outliers(ser, low_perc, high_perc):
    low, high = ser.quantile([low_perc, high_perc])
    print(low_perc, '%ile: ', low, '|', high_perc, '%ile: ', high)
    ser[ser < low] = low
    ser[ser > high] = high
    return(ser)

capped_ser = cap_outliers(ser, .05, .95)

0.05 %ile:  0.016049294076965887 | 0.95 %ile:  63.876672220183934


Q55

In [148]:
df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10,-1))

In [149]:
arr = df[df > 0].values.flatten()
arr_qualified = arr[~np.isnan(arr)]

n = int(np.floor(arr_qualified.shape[0]**.5))

top_indexes = np.argsort(arr_qualified)[::-1]
output = np.take(arr_qualified, sorted(top_indexes[:n**2])).reshape(n, -1)
print(output)

[[28. 23. 26. 18.  9. 44. 47. 44.]
 [12.  6. 12. 43. 17. 28.  8. 46.]
 [18. 44. 19. 35. 35.  6. 49. 33.]
 [25. 38. 35. 47. 31. 16. 18.  8.]
 [12.  5. 48. 48. 39. 27. 40.  7.]
 [16.  6.  7. 31. 33. 34. 28. 33.]
 [26. 27. 33. 27. 10. 43. 20. 13.]
 [33. 37.  7. 22. 19. 18. 13. 18.]]


Q56

In [150]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))

In [153]:
def swap_rows(df, i1, i2):
    a, b = df.iloc[i1, :].copy(), df.iloc[i2, :].copy()
    df.iloc[i1, :], df.iloc[i2, :] = b, a
    return df

print(swap_rows(df, 1, 2))

    0   1   2   3   4
0   0   1   2   3   4
1  10  11  12  13  14
2   5   6   7   8   9
3  15  16  17  18  19
4  20  21  22  23  24


Q57

In [3]:
import numpy as np
df = pd.DataFrame(np.arange(25).reshape(5, -1))

In [7]:
df = df.iloc[::-1,:]

In [8]:
df

0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4

Q58

In [9]:
df = pd.DataFrame(np.arange(25).reshape(5,-1), columns=list('abcde'))

In [10]:
df_onehot = pd.concat([pd.get_dummies(df['a']), df[list('bcde')]], axis=1)
print(df_onehot)

   0  5  10  15  20   b   c   d   e
0  1  0   0   0   0   1   2   3   4
1  0  1   0   0   0   6   7   8   9
2  0  0   1   0   0  11  12  13  14
3  0  0   0   1   0  16  17  18  19
4  0  0   0   0   1  21  22  23  24


Q59

In [11]:
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1))

In [12]:
print('Column with highest row maxes: ', df.apply(np.argmax, axis=1).value_counts().index[0])

Column with highest row maxes:  1


C:\Users\dhxog\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:56: FutureWarning: 
The current behaviour of 'Series.argmax' is deprecated, use 'idxmax'
instead.
The behavior of 'argmax' will be corrected to return the positional
maximum in the future. For now, use 'series.values.argmax' or
'np.argmax(np.array(values))' to get the position of the maximum
row.
  return getattr(obj, method)(*args, **kwds)


Q60

In [13]:
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1), columns=list('pqrs'), index=list('abcdefghij'))

In [17]:
nearest_rows = []
nearest_distance = []

# iterate rows.
for i, row in df.iterrows():
    curr = row
    rest = df.drop(i)
    e_dists = {}  # init dict to store euclidean dists for current row.
    # iterate rest of rows for current row
    for j, contestant in rest.iterrows():
        # compute euclidean dist and update e_dists
        e_dists.update({j: round(np.linalg.norm(curr.values - contestant.values))})
    # update nearest row to current row and the distance value
    nearest_rows.append(max(e_dists, key=e_dists.get))
    nearest_distance.append(max(e_dists.values()))

df['nearest_row'] = nearest_rows
df['dist'] = nearest_distance

TypeError: unsupported operand type(s) for -: 'str' and 'str'

Q61

In [19]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1), columns=list('pqrstuvwxy'), index=list('abcdefgh'))

In [20]:
df

p   q   r   s   t   u   v   w   x   y
a   5  50  14   2  88  61  76  86  76  95
b  34  28  13  39  66  98  41  29  66   5
c  87  58  72   6  20  93  86  10  98  35
d  28  99   8  30  45  45  36  15  45  51
e   7  81  15  46  28  65  20   5  66  96
f  62  13  59  44  28   9  97  52  99  66
g  77  69   7  18  46  54  54   1  17   6
h  45  23  98  17  92  53  75  32  12   4

In [22]:
abs_corrmat = np.abs(df.corr())
max_corr = abs_corrmat.apply(lambda x: sorted(x)[-2])
print('Maximum Correlation possible for each column: ', np.round(max_corr.tolist(), 2))

Maximum Correlation possible for each column:  [0.6  0.65 0.67 0.46 0.56 0.31 0.67 0.56 0.54 0.6 ]


Q62

In [23]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

In [24]:
min_by_max = df.apply(lambda x: np.min(x)/np.max(x), axis=1)

In [25]:
min_by_max

0    0.123596
1    0.011236
2    0.052083
3    0.021505
4    0.126582
5    0.020202
6    0.071429
7    0.313131
dtype: float64

Q63

In [26]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

In [29]:
out = df.apply(lambda x: x.sort_values().unique()[-2], axis=1)
df['penultimate'] = out
print(df)

    0   1   2   3   4   5   6   7   8   9  penultimate
0  85   8  95  93  18   8  18  12  82   2           93
1  37  36  64  20  41  77  16  20  74  32           74
2  52  36  10  23  94  20  52  15  17  84           84
3  29  47  83  27  32  84  21  48  77  62           83
4  96  58  14  52  50  19  45   7  28  67           67
5  14  67  89  92  87  23  35  91  24   8           91
6  57  42  69  21   5  57  84  83  84  96           84
7  97  58  56  31  81  66   4  40  45  47           81


Q64

In [30]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

In [31]:
out1 = df.apply(lambda x: ((x - x.mean())/x.std()).round(2))

In [32]:
print('Solution Q1\n', out1)

Solution Q1
       0     1     2     3     4     5     6     7     8     9
0 -0.22 -1.40 -0.77  1.00  1.44 -1.01 -0.13  1.00  0.17  1.75
1  0.87  1.45  0.77 -1.14 -0.51  0.51  1.58  1.53  1.46  0.67
2 -1.12 -0.14 -1.64 -0.47 -0.51  0.66  0.07  0.03 -0.43 -0.55
3 -0.77  0.03 -0.47  1.36 -1.52  1.38  0.33 -1.03  0.85  0.03
4 -0.99  1.16  1.01 -0.98  0.39  0.33  1.12  0.83  0.28  0.24
5 -0.19  0.43  1.23 -0.03  0.65  0.55 -0.79 -1.00 -1.68 -0.22
6  1.64 -0.44  0.37  1.04  0.90 -1.05 -0.79 -0.63  0.32 -0.19
7  0.80 -1.10 -0.50 -0.78 -0.84 -1.37 -1.38 -0.73 -0.96 -1.74


In [33]:
out2 = df.apply(lambda x: ((x.max() - x)/(x.max() - x.min())).round(2))
print('Solution Q2\n', out2)  

Solution Q2
       0     1     2     3     4     5     6     7     8     9
0  0.67  1.00  0.70  0.14  0.00  0.87  0.58  0.21  0.41  0.00
1  0.28  0.00  0.16  1.00  0.66  0.32  0.00  0.00  0.00  0.31
2  1.00  0.56  1.00  0.73  0.66  0.26  0.51  0.58  0.60  0.66
3  0.87  0.50  0.59  0.00  1.00  0.00  0.42  1.00  0.19  0.49
4  0.95  0.10  0.08  0.94  0.35  0.38  0.16  0.27  0.37  0.43
5  0.66  0.36  0.00  0.56  0.27  0.30  0.80  0.99  1.00  0.57
6  0.00  0.66  0.30  0.13  0.18  0.88  0.80  0.84  0.36  0.56
7  0.30  0.90  0.60  0.86  0.77  1.00  1.00  0.88  0.77  1.00


Q65

In [34]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

In [37]:
[df.iloc[i].corr(df.iloc[i+1]).round(2) for i in range(df.shape[0])[:-1]]

[-0.18, -0.12, 0.87, -0.14, 0.12, 0.4, 0.12]

Q66

In [38]:
df = pd.DataFrame(np.random.randint(1,100, 100).reshape(10, -1))

In [39]:
for i in range(df.shape[0]):
    df.iat[i, i] = 0
    df.iat[df.shape[0]-i-1, i] = 0

In [41]:
df

0   1   2   3   4   5   6   7   8   9
0   0  69  84  40  30  57  44  37  63   0
1  10   0   5  34  77  54  60  28   0  89
2  99  59   0  78  13  24  78   0  11  59
3  32  91  58   0  27  93   0  68  81  95
4  58  67   9  49   0   0  77   1  11  29
5  68  42  33  41   0   0  71  24  31  54
6  25  93  38   0  97  55   0  11   5  30
7  22  32   0  66   1  39   9   0   7  18
8  75   0  27  85  42  63  82  45   0  92
9   0  25  47  80  63  66  33  94  28   0

Q67

In [42]:
df = pd.DataFrame({'col1': ['apple', 'banana', 'orange'] * 3,
                   'col2': np.random.rand(9),
                   'col3': np.random.randint(0, 15, 9)})

df_grouped = df.groupby(['col1'])

In [43]:
df_grouped.get_group('apple')


col1      col2  col3
0  apple  0.109911     8
3  apple  0.825882     9
6  apple  0.758140    13

Q68

In [46]:
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'taste': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})

In [47]:
df_grpd = df['taste'].groupby(df.fruit)
df_grpd.get_group('banana').sort_values().iloc[-2]

0.5138209106233621

Q69

In [48]:
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})


In [49]:
out = df.groupby('fruit', as_index=False)['price'].mean()
print(out)

    fruit      price
0   apple  11.000000
1  banana   7.666667
2  orange   3.333333


Q70

In [50]:
df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})

In [52]:
pd.merge(df1, df2, how='inner', left_on=['fruit', 'weight'], right_on=['pazham', 'kilo'], suffixes=['_left', '_right'])

fruit weight  price_left  pazham  kilo  price_right
0   apple   high           4   apple  high           10
1   apple   high          13   apple  high           10
2   apple   high          14   apple  high           10
3  orange    low          13  orange   low            5
4  orange    low           7  orange   low            5
5  orange    low           3  orange   low            5

Q71

In [53]:
df1 = pd.DataFrame({'fruit': ['apple', 'orange', 'banana'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.arange(9)})

df2 = pd.DataFrame({'fruit': ['apple', 'orange', 'pine'] * 2,
                    'weight': ['high', 'medium'] * 3,
                    'price': np.arange(6)})

In [54]:
print(df1[~df1.isin(df2).all(1)])

    fruit  weight  price
2  banana     low      2
3   apple    high      3
4  orange  medium      4
5  banana     low      5
6   apple    high      6
7  orange  medium      7
8  banana     low      8


Q72

In [55]:
df = pd.DataFrame({'fruit1': np.random.choice(['apple', 'orange', 'banana'], 10),
                    'fruit2': np.random.choice(['apple', 'orange', 'banana'], 10)})


In [56]:
np.where(df.fruit1 == df.fruit2)

(array([3, 5, 6], dtype=int64),)

Q73

In [57]:
df = pd.DataFrame(np.random.randint(1, 100, 20).reshape(-1, 4), columns = list('abcd'))

In [58]:
df['a_lag1'] = df['a'].shift(1)
df['b_lead1'] = df['b'].shift(-1)
print(df)

    a   b   c   d  a_lag1  b_lead1
0  82  33  27  12     NaN     19.0
1  60  19  21  31    82.0     19.0
2  90  19  28  33    60.0     99.0
3   8  99  54  94    90.0     41.0
4  15  41  12  56     8.0      NaN


Q74

In [60]:
df = pd.DataFrame(np.random.randint(1, 10, 20).reshape(-1, 4), columns = list('abcd'))

In [61]:
pd.value_counts(df.values.ravel())

9    4
1    4
7    3
4    3
3    2
8    1
6    1
5    1
2    1
dtype: int64

Q75

In [62]:
df = pd.DataFrame(["STD, City    State",
"33, Kolkata    West Bengal",
"44, Chennai    Tamil Nadu",
"40, Hyderabad    Telengana",
"80, Bangalore    Karnataka"], columns=['row'])

In [63]:
df_out = df.row.str.split(',|\t', expand=True)


In [64]:
new_header = df_out.iloc[0]
df_out = df_out[1:]
df_out.columns = new_header
print(df_out)

0 STD            City    State
1  33   Kolkata    West Bengal
2  44    Chennai    Tamil Nadu
3  40   Hyderabad    Telengana
4  80   Bangalore    Karnataka
